name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: gcc lookup.c -o lookup
    - name: make executable
      run: chmod +x lookup
    - name: lookup_google
      run: ./lookup google.com
